name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  unit-test-plugin-helm:
    name: Unit Tests - Helm Plugin
    uses: ./.github/workflows/job-unit-test.yml
    with:
      plugin_id: helm
      plugin_name: Helm
    secrets: inherit

  build-check-plugin-helm:
    name: Build Check - Helm Plugin
    uses: ./.github/workflows/job-build-check.yml
    with:
      plugin_id: helm
      RUNNER: ubuntu-latest
    secrets: inherit

  unit-test-plugin-resources-monitor:
    name: Unit Tests - Resources Monitor Plugin
    uses: ./.github/workflows/job-unit-test.yml
    with:
      plugin_id: resources-monitor
      plugin_name: Resources Monitor
    secrets: inherit

  build-check-plugin-resources-monitor:
    name: Build Check - Resources Monitor Plugin
    uses: ./.github/workflows/job-build-check.yml
    with:
      plugin_id: resources-monitor
      RUNNER: ubuntu-latest
    secrets: inherit
